# This file was generated by GoReleaser. DO NOT EDIT.
cask "signadot-cli" do
  name "signadot-cli"
  desc "Command-line interface for Signadot"
  homepage "https://signadot.com"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "signadot"

  on_macos do
    on_intel do
      url "https://github.com/signadot/cli/releases/download/v#{version}/signadot-cli_mcp_darwin_amd64.tar.gz"
      sha256 "364ceaa11afd3cfd1dc34261382322db336ab4d4fdaa251f14a590f5a29e03a6"
    end
    on_arm do
      url "https://github.com/signadot/cli/releases/download/v#{version}/signadot-cli_mcp_darwin_arm64.tar.gz"
      sha256 "330c69f7143db03a2798328fb31fd0a4afd71f0b7b6de6f4b8a2e2ead990047a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/signadot/cli/releases/download/v#{version}/signadot-cli_mcp_linux_amd64.tar.gz"
      sha256 "df4f5e7c5db65d81e528a8cd5105738423d9e001a6856cf8e6297b29ddfafb0c"
    end
    on_arm do
      url "https://github.com/signadot/cli/releases/download/v#{version}/signadot-cli_mcp_linux_arm64.tar.gz"
      sha256 "fb8dfa04fa3907a96e993506a099917241cebc0912571c5a4ef0ccf6018e1ed7"
    end
  end

  # No zap stanza required
end
