# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SignadotCli < Formula
  desc "Command-line interface for Signadot"
  homepage "https://signadot.com"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/signadot/cli/releases/download/v1.3.0/signadot-cli_darwin_arm64.tar.gz"
      sha256 "75aaf361193338c39df6f2ad85cbdd28ba084f3c416244590de4a17290eb075b"

      def install
        bin.install "signadot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/signadot/cli/releases/download/v1.3.0/signadot-cli_darwin_amd64.tar.gz"
      sha256 "758c24c507850a9098a733d58225e5ecc3f93a4937512b59df91a3be6e45f755"

      def install
        bin.install "signadot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/signadot/cli/releases/download/v1.3.0/signadot-cli_linux_arm64.tar.gz"
      sha256 "1b5bb4fb687ef4b0b5b82ec91a2570926ce72edfcda4ee051434b393e12e1179"

      def install
        bin.install "signadot"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/signadot/cli/releases/download/v1.3.0/signadot-cli_linux_amd64.tar.gz"
      sha256 "09794d469162747d14ef65b0df523c7649c97d96144b55a6905034c5b60f7727"

      def install
        bin.install "signadot"
      end
    end
  end
end
