# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SignadotCli < Formula
  desc "Command-line interface for Signadot"
  homepage "https://signadot.com"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/signadot/cli/releases/download/v0.3.2/signadot-cli_darwin_amd64.tar.gz"
      sha256 "2c9cb8d30349d9a2d07525d5f87ca85857eeda28bac483784d5e192fd0f95529"
    end
    if Hardware::CPU.arm?
      url "https://github.com/signadot/cli/releases/download/v0.3.2/signadot-cli_darwin_arm64.tar.gz"
      sha256 "9cc86d82a1b56c181ee20f264c6be803552a094bfeba17402d285451082423e6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/signadot/cli/releases/download/v0.3.2/signadot-cli_linux_amd64.tar.gz"
      sha256 "70c77b27641c08dabef499df1649f157b283d2d1b2b5c90b4f668c9184ef3cd4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/signadot/cli/releases/download/v0.3.2/signadot-cli_linux_arm64.tar.gz"
      sha256 "2a684be9f03e52d748fdb267c141c0cc668849477d04a5c0f93f27f1d4ecb956"
    end
  end

  def install
    bin.install "signadot"
  end
end
